parameters:
#liip_imagine.optipng.binary: /usr/bin/optipng
liip_imagine:
    webp:
        generate: true
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    # your filter sets are defined here
    filter_sets:
        cache: ~
        logo:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 40

        modele:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                relative_resize:
                    heighten: 300

        logoheader:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 70

        picture:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 100

        carte:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 440

        carousel:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                fixed:
                    height: 700
                    width: 1980

        perso:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                fixed:
                    height: 500
                    width: 1280
                filter: ["brightness", 40]

        invitation:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                fixed:
                    height: 400
                    width: 1980
                filter: ["brightness", -40]

        blog:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    heighten: 300

        lazy:
            jpeg_quality: 20
            png_compression_level: 1
            filters:
                relative_resize:
                    widen: 60

        fullhd:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 1920

        hd:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 1280
        grande:
        grand:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 900

        moyen:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 600

        moyencarree:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [550, 550]
                    mode: outbound

        petit:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 300

        petitcarree:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [300, 300]
                    mode: outbound

        minicarree:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [200, 200]
                    mode: outbound

        mini:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 100

        icone:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 60

        icone_vert:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 32
                filter: ["colorize", "#6e9755"]

        label:
            jpeg_quality: 80
            png_compression_level: 6
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 100

        favicon:
            png_compression_level: 6
            format: png
            filters:
                relative_resize:
                    widen: 32

        #pngspeed : #install optipng by apt
        #    quality : 75
        #    post_processors:
        #        optipng: { strip_all: false, level: 5 }     #on garde les exif
