version: '3'
services:
  $PWD:
    image: cadotinfo/symfony5
    container_name: $PWD
    volumes:
      - .:/app
    networks:
      - web
    restart: always
    ports:
      - 80


networks:
  web:
    external: true
