version: '3'
services:
  test2:
    image: cadotinfo/symfony5
    container_name: test2
    volumes:
      - .:/app
    networks:
      - web
    restart: always
    ports:
      - 80
 
networks:
  web:
    external: true
