version: '3'
services:
  test:
    image: cadotinfo/symfony5
    container_name: test
    volumes:
      - .:/app
    networks:
      - web
    restart: always
    ports:
      - 80


networks:
  web:
    external: true
